[package]
name = "yaml-parser"
version = "0.1.0"
categories = ["encoding", "parser-implementations", "no-std"]
keywords = ["yaml"]
edition = "2021"

[dependencies]

[dev-dependencies]
serde = { version = "1.0.196", features = ["serde_derive"] }
serde_json = "1.0.112"
serde_yaml = "0.9.30"
