[package]
name = "yaml-parser"
version = "0.1.0"
categories = ["encoding", "parser-implementations", "no-std"]
keywords = ["yaml"]
edition = "2021"

[dependencies]
tracing = { version = "0.1.40" }

[dev-dependencies]
tracing-subscriber = "0.3.18"
