case!(case_229q, "yaml-test-suite/229Q");
case!(case_236b, "yaml-test-suite/236B", fail: true);
case!(case_26dv, "yaml-test-suite/26DV");
case!(case_27na, "yaml-test-suite/27NA");
case!(case_2auy, "yaml-test-suite/2AUY");
case!(case_2cms, "yaml-test-suite/2CMS", fail: true);
case!(case_2ebw, "yaml-test-suite/2EBW");
case!(case_2g84_00, "yaml-test-suite/2G84/00", fail: true);
case!(case_2g84_01, "yaml-test-suite/2G84/01", fail: true);
case!(case_2g84_02, "yaml-test-suite/2G84/02");
case!(case_2g84_03, "yaml-test-suite/2G84/03");
case!(case_2jqs, "yaml-test-suite/2JQS");
case!(case_2lfx, "yaml-test-suite/2LFX");
case!(case_2sxe, "yaml-test-suite/2SXE");
case!(case_2xxw, "yaml-test-suite/2XXW");
case!(case_33x3, "yaml-test-suite/33X3");
case!(case_35kp, "yaml-test-suite/35KP");
case!(case_36f6, "yaml-test-suite/36F6");
case!(case_3alj, "yaml-test-suite/3ALJ");
case!(case_3gzx, "yaml-test-suite/3GZX");
case!(case_3hfz, "yaml-test-suite/3HFZ", fail: true);
case!(case_3myt, "yaml-test-suite/3MYT");
case!(case_3r3p, "yaml-test-suite/3R3P");
case!(case_3rln_00, "yaml-test-suite/3RLN/00");
case!(case_3rln_01, "yaml-test-suite/3RLN/01");
case!(case_3rln_02, "yaml-test-suite/3RLN/02");
case!(case_3rln_03, "yaml-test-suite/3RLN/03");
case!(case_3rln_04, "yaml-test-suite/3RLN/04");
case!(case_3rln_05, "yaml-test-suite/3RLN/05");
case!(case_3uys, "yaml-test-suite/3UYS");
case!(case_4abk, "yaml-test-suite/4ABK");
case!(case_4cqq, "yaml-test-suite/4CQQ");
case!(case_4ejs, "yaml-test-suite/4EJS", fail: true);
case!(case_4fj6, "yaml-test-suite/4FJ6");
case!(case_4gc6, "yaml-test-suite/4GC6");
case!(case_4h7k, "yaml-test-suite/4H7K", fail: true);
case!(case_4hvu, "yaml-test-suite/4HVU", fail: true);
case!(case_4jvg, "yaml-test-suite/4JVG", fail: true);
case!(case_4muz_00, "yaml-test-suite/4MUZ/00");
case!(case_4muz_01, "yaml-test-suite/4MUZ/01");
case!(case_4muz_02, "yaml-test-suite/4MUZ/02");
case!(case_4q9f, "yaml-test-suite/4Q9F");
case!(case_4qfq, "yaml-test-suite/4QFQ");
case!(case_4rwc, "yaml-test-suite/4RWC");
case!(case_4uyu, "yaml-test-suite/4UYU");
case!(case_4v8u, "yaml-test-suite/4V8U");
case!(case_4wa9, "yaml-test-suite/4WA9");
case!(case_4zym, "yaml-test-suite/4ZYM");
case!(case_52dl, "yaml-test-suite/52DL");
case!(case_54t7, "yaml-test-suite/54T7");
case!(case_55wf, "yaml-test-suite/55WF", fail: true);
case!(case_565n, "yaml-test-suite/565N");
case!(case_57h4, "yaml-test-suite/57H4");
case!(case_58mp, "yaml-test-suite/58MP");
case!(case_5bvj, "yaml-test-suite/5BVJ");
case!(case_5c5m, "yaml-test-suite/5C5M");
case!(case_5gbf, "yaml-test-suite/5GBF");
case!(case_5kje, "yaml-test-suite/5KJE");
case!(case_5llu, "yaml-test-suite/5LLU", fail: true);
case!(case_5mud, "yaml-test-suite/5MUD");
case!(case_5nyz, "yaml-test-suite/5NYZ");
case!(case_5t43, "yaml-test-suite/5T43");
case!(case_5trb, "yaml-test-suite/5TRB", fail: true);
case!(case_5tym, "yaml-test-suite/5TYM");
case!(case_5u3a, "yaml-test-suite/5U3A", fail: true);
case!(case_5we3, "yaml-test-suite/5WE3");
case!(case_62ez, "yaml-test-suite/62EZ", fail: true);
case!(case_652z, "yaml-test-suite/652Z");
case!(case_65wh, "yaml-test-suite/65WH");
case!(case_6bct, "yaml-test-suite/6BCT");
case!(case_6bfj, "yaml-test-suite/6BFJ");
case!(case_6ca3, "yaml-test-suite/6CA3");
case!(case_6ck3, "yaml-test-suite/6CK3");
case!(case_6fwr, "yaml-test-suite/6FWR");
case!(case_6h3v, "yaml-test-suite/6H3V");
case!(case_6hb6, "yaml-test-suite/6HB6");
case!(case_6jqw, "yaml-test-suite/6JQW");
case!(case_6jtt, "yaml-test-suite/6JTT", fail: true);
case!(case_6jwb, "yaml-test-suite/6JWB");
case!(case_6kgn, "yaml-test-suite/6KGN");
case!(case_6lvf, "yaml-test-suite/6LVF");
case!(case_6m2f, "yaml-test-suite/6M2F");
case!(case_6pbe, "yaml-test-suite/6PBE");
case!(case_6s55, "yaml-test-suite/6S55", fail: true);
case!(case_6sla, "yaml-test-suite/6SLA");
case!(case_6vjk, "yaml-test-suite/6VJK");
case!(case_6wlz, "yaml-test-suite/6WLZ");
case!(case_6wpf, "yaml-test-suite/6WPF");
case!(case_6xdy, "yaml-test-suite/6XDY");
case!(case_6zkb, "yaml-test-suite/6ZKB");
case!(case_735y, "yaml-test-suite/735Y");
case!(case_74h7, "yaml-test-suite/74H7");
case!(case_753e, "yaml-test-suite/753E");
case!(case_7a4e, "yaml-test-suite/7A4E");
case!(case_7bmt, "yaml-test-suite/7BMT");
case!(case_7bub, "yaml-test-suite/7BUB");
case!(case_7fwl, "yaml-test-suite/7FWL");
case!(case_7lbh, "yaml-test-suite/7LBH", fail: true);
case!(case_7mnf, "yaml-test-suite/7MNF", fail: true);
case!(case_7t8x, "yaml-test-suite/7T8X");
case!(case_7tmg, "yaml-test-suite/7TMG");
case!(case_7w2p, "yaml-test-suite/7W2P");
case!(case_7z25, "yaml-test-suite/7Z25");
case!(case_7zz5, "yaml-test-suite/7ZZ5");
case!(case_82an, "yaml-test-suite/82AN");
case!(case_87e4, "yaml-test-suite/87E4");
case!(case_8cwc, "yaml-test-suite/8CWC");
case!(case_8g76, "yaml-test-suite/8G76");
case!(case_8kb6, "yaml-test-suite/8KB6");
case!(case_8mk2, "yaml-test-suite/8MK2");
case!(case_8qbe, "yaml-test-suite/8QBE");
case!(case_8udb, "yaml-test-suite/8UDB");
case!(case_8xdj, "yaml-test-suite/8XDJ", fail: true);
case!(case_8xyn, "yaml-test-suite/8XYN");
case!(case_93jh, "yaml-test-suite/93JH");
case!(case_93wf, "yaml-test-suite/93WF");
case!(case_96l6, "yaml-test-suite/96L6");
case!(case_96nn_00, "yaml-test-suite/96NN/00");
case!(case_96nn_01, "yaml-test-suite/96NN/01");
case!(case_98yd, "yaml-test-suite/98YD");
case!(case_9bxh, "yaml-test-suite/9BXH");
case!(case_9c9n, "yaml-test-suite/9C9N", fail: true);
case!(case_9cwy, "yaml-test-suite/9CWY", fail: true);
case!(case_9dxl, "yaml-test-suite/9DXL");
case!(case_9fmg, "yaml-test-suite/9FMG");
case!(case_9hcy, "yaml-test-suite/9HCY", fail: true);
case!(case_9j7a, "yaml-test-suite/9J7A");
case!(case_9jba, "yaml-test-suite/9JBA", fail: true);
case!(case_9kax, "yaml-test-suite/9KAX");
case!(case_9kbc, "yaml-test-suite/9KBC", fail: true);
case!(case_9mag, "yaml-test-suite/9MAG", fail: true);
case!(case_9mma, "yaml-test-suite/9MMA", fail: true);
case!(case_9mmw, "yaml-test-suite/9MMW");
case!(case_9mqt_00, "yaml-test-suite/9MQT/00");
case!(case_9mqt_01, "yaml-test-suite/9MQT/01", fail: true);
case!(case_9sa2, "yaml-test-suite/9SA2");
case!(case_9shh, "yaml-test-suite/9SHH");
case!(case_9tfx, "yaml-test-suite/9TFX");
case!(case_9u5k, "yaml-test-suite/9U5K");
case!(case_9wxw, "yaml-test-suite/9WXW");
case!(case_9yrd, "yaml-test-suite/9YRD");
case!(case_a2m4, "yaml-test-suite/A2M4");
case!(case_a6f9, "yaml-test-suite/A6F9");
case!(case_a984, "yaml-test-suite/A984");
case!(case_ab8u, "yaml-test-suite/AB8U");
case!(case_avm7, "yaml-test-suite/AVM7");
case!(case_az63, "yaml-test-suite/AZ63");
case!(case_azw3, "yaml-test-suite/AZW3");
case!(case_b3hg, "yaml-test-suite/B3HG");
case!(case_b63p, "yaml-test-suite/B63P", fail: true);
case!(case_bd7l, "yaml-test-suite/BD7L", fail: true);
case!(case_bec7, "yaml-test-suite/BEC7");
case!(case_bf9h, "yaml-test-suite/BF9H", fail: true);
case!(case_bs4k, "yaml-test-suite/BS4K", fail: true);
case!(case_bu8l, "yaml-test-suite/BU8L");
case!(case_c2dt, "yaml-test-suite/C2DT");
case!(case_c2sp, "yaml-test-suite/C2SP", fail: true);
case!(case_c4hz, "yaml-test-suite/C4HZ");
case!(case_cc74, "yaml-test-suite/CC74");
case!(case_cfd4, "yaml-test-suite/CFD4");
case!(case_cml9, "yaml-test-suite/CML9", fail: true);
case!(case_cn3r, "yaml-test-suite/CN3R");
case!(case_cpz3, "yaml-test-suite/CPZ3");
case!(case_cq3w, "yaml-test-suite/CQ3W", fail: true);
case!(case_ct4q, "yaml-test-suite/CT4Q");
case!(case_ctn5, "yaml-test-suite/CTN5", fail: true);
case!(case_cup7, "yaml-test-suite/CUP7");
case!(case_cvw2, "yaml-test-suite/CVW2", fail: true);
case!(case_cxx2, "yaml-test-suite/CXX2", fail: true);
case!(case_d49q, "yaml-test-suite/D49Q", fail: true);
case!(case_d83l, "yaml-test-suite/D83L");
case!(case_d88j, "yaml-test-suite/D88J");
case!(case_d9tu, "yaml-test-suite/D9TU");
case!(case_dbg4, "yaml-test-suite/DBG4");
case!(case_dc7x, "yaml-test-suite/DC7X");
case!(case_de56_00, "yaml-test-suite/DE56/00");
case!(case_de56_01, "yaml-test-suite/DE56/01");
case!(case_de56_02, "yaml-test-suite/DE56/02");
case!(case_de56_03, "yaml-test-suite/DE56/03");
case!(case_de56_04, "yaml-test-suite/DE56/04");
case!(case_de56_05, "yaml-test-suite/DE56/05");
case!(case_dff7, "yaml-test-suite/DFF7");
case!(case_dhp8, "yaml-test-suite/DHP8");
case!(case_dk3j, "yaml-test-suite/DK3J");
case!(case_dk4h, "yaml-test-suite/DK4H", fail: true);
case!(case_dk95_00, "yaml-test-suite/DK95/00");
case!(case_dk95_01, "yaml-test-suite/DK95/01", fail: true);
case!(case_dk95_02, "yaml-test-suite/DK95/02");
case!(case_dk95_03, "yaml-test-suite/DK95/03");
case!(case_dk95_04, "yaml-test-suite/DK95/04");
case!(case_dk95_05, "yaml-test-suite/DK95/05");
case!(case_dk95_06, "yaml-test-suite/DK95/06", fail: true);
case!(case_dk95_07, "yaml-test-suite/DK95/07");
case!(case_dk95_08, "yaml-test-suite/DK95/08");
case!(case_dmg6, "yaml-test-suite/DMG6", fail: true);
case!(case_dwx9, "yaml-test-suite/DWX9");
case!(case_e76z, "yaml-test-suite/E76Z");
case!(case_eb22, "yaml-test-suite/EB22", fail: true);
case!(case_ehf6, "yaml-test-suite/EHF6");
case!(case_ew3v, "yaml-test-suite/EW3V", fail: true);
case!(case_ex5h, "yaml-test-suite/EX5H");
case!(case_exg3, "yaml-test-suite/EXG3");
case!(case_f2c7, "yaml-test-suite/F2C7");
case!(case_f3cp, "yaml-test-suite/F3CP");
case!(case_f6mc, "yaml-test-suite/F6MC");
case!(case_f8f9, "yaml-test-suite/F8F9");
case!(case_fbc9, "yaml-test-suite/FBC9");
case!(case_fh7j, "yaml-test-suite/FH7J");
case!(case_fp8r, "yaml-test-suite/FP8R");
case!(case_fq7f, "yaml-test-suite/FQ7F");
case!(case_frk4, "yaml-test-suite/FRK4");
case!(case_fta2, "yaml-test-suite/FTA2");
case!(case_fup4, "yaml-test-suite/FUP4");
case!(case_g4rs, "yaml-test-suite/G4RS");
case!(case_g5u8, "yaml-test-suite/G5U8", fail: true);
case!(case_g7je, "yaml-test-suite/G7JE", fail: true);
case!(case_g992, "yaml-test-suite/G992");
case!(case_g9hc, "yaml-test-suite/G9HC", fail: true);
case!(case_gdy7, "yaml-test-suite/GDY7", fail: true);
case!(case_gh63, "yaml-test-suite/GH63");
case!(case_gt5m, "yaml-test-suite/GT5M", fail: true);
case!(case_h2rw, "yaml-test-suite/H2RW");
case!(case_h3z8, "yaml-test-suite/H3Z8");
case!(case_h7j7, "yaml-test-suite/H7J7", fail: true);
case!(case_h7tq, "yaml-test-suite/H7TQ", fail: true);
case!(case_hm87_00, "yaml-test-suite/HM87/00");
case!(case_hm87_01, "yaml-test-suite/HM87/01");
case!(case_hmk4, "yaml-test-suite/HMK4");
case!(case_hmq5, "yaml-test-suite/HMQ5");
case!(case_hre5, "yaml-test-suite/HRE5", fail: true);
case!(case_hs5t, "yaml-test-suite/HS5T");
case!(case_hu3p, "yaml-test-suite/HU3P", fail: true);
case!(case_hwv9, "yaml-test-suite/HWV9");
case!(case_j3bt, "yaml-test-suite/J3BT");
case!(case_j5uc, "yaml-test-suite/J5UC");
case!(case_j7pz, "yaml-test-suite/J7PZ");
case!(case_j7vc, "yaml-test-suite/J7VC");
case!(case_j9hz, "yaml-test-suite/J9HZ");
case!(case_jef9_00, "yaml-test-suite/JEF9/00");
case!(case_jef9_01, "yaml-test-suite/JEF9/01");
case!(case_jef9_02, "yaml-test-suite/JEF9/02");
case!(case_jhb9, "yaml-test-suite/JHB9");
case!(case_jkf3, "yaml-test-suite/JKF3", fail: true);
case!(case_jq4r, "yaml-test-suite/JQ4R");
case!(case_jr7v, "yaml-test-suite/JR7V");
case!(case_js2j, "yaml-test-suite/JS2J");
case!(case_jtv5, "yaml-test-suite/JTV5");
case!(case_jy7z, "yaml-test-suite/JY7Z", fail: true);
case!(case_k3wx, "yaml-test-suite/K3WX");
case!(case_k4su, "yaml-test-suite/K4SU");
case!(case_k527, "yaml-test-suite/K527");
case!(case_k54u, "yaml-test-suite/K54U");
case!(case_k858, "yaml-test-suite/K858");
case!(case_kh5v_00, "yaml-test-suite/KH5V/00");
case!(case_kh5v_01, "yaml-test-suite/KH5V/01");
case!(case_kh5v_02, "yaml-test-suite/KH5V/02");
case!(case_kk5p, "yaml-test-suite/KK5P");
case!(case_kmk3, "yaml-test-suite/KMK3");
case!(case_ks4u, "yaml-test-suite/KS4U", fail: true);
case!(case_kss4, "yaml-test-suite/KSS4");
case!(case_l24t_00, "yaml-test-suite/L24T/00");
case!(case_l24t_01, "yaml-test-suite/L24T/01");
case!(case_l383, "yaml-test-suite/L383");
case!(case_l94m, "yaml-test-suite/L94M");
case!(case_l9u5, "yaml-test-suite/L9U5");
case!(case_le5a, "yaml-test-suite/LE5A");
case!(case_lhl4, "yaml-test-suite/LHL4", fail: true);
case!(case_lp6e, "yaml-test-suite/LP6E");
case!(case_lqz7, "yaml-test-suite/LQZ7");
case!(case_lx3p, "yaml-test-suite/LX3P");
case!(case_m29m, "yaml-test-suite/M29M");
case!(case_m2n8_00, "yaml-test-suite/M2N8/00");
case!(case_m2n8_01, "yaml-test-suite/M2N8/01");
case!(case_m5c3, "yaml-test-suite/M5C3");
case!(case_m5dy, "yaml-test-suite/M5DY");
case!(case_m6yh, "yaml-test-suite/M6YH");
case!(case_m7a3, "yaml-test-suite/M7A3");
case!(case_m7nx, "yaml-test-suite/M7NX");
case!(case_m9b4, "yaml-test-suite/M9B4");
case!(case_mjs9, "yaml-test-suite/MJS9");
case!(case_mus6_00, "yaml-test-suite/MUS6/00", fail: true);
case!(case_mus6_01, "yaml-test-suite/MUS6/01", fail: true);
case!(case_mus6_02, "yaml-test-suite/MUS6/02");
case!(case_mus6_03, "yaml-test-suite/MUS6/03");
case!(case_mus6_04, "yaml-test-suite/MUS6/04");
case!(case_mus6_05, "yaml-test-suite/MUS6/05");
case!(case_mus6_06, "yaml-test-suite/MUS6/06");
case!(case_mxs3, "yaml-test-suite/MXS3");
case!(case_myw6, "yaml-test-suite/MYW6");
case!(case_mzx3, "yaml-test-suite/MZX3");
case!(case_n4jp, "yaml-test-suite/N4JP", fail: true);
case!(case_n782, "yaml-test-suite/N782", fail: true);
case!(case_nat4, "yaml-test-suite/NAT4");
case!(case_nb6z, "yaml-test-suite/NB6Z");
case!(case_nhx8, "yaml-test-suite/NHX8");
case!(case_nj66, "yaml-test-suite/NJ66");
case!(case_nkf9, "yaml-test-suite/NKF9");
case!(case_np9h, "yaml-test-suite/NP9H");
case!(case_p2ad, "yaml-test-suite/P2AD");
case!(case_p2eq, "yaml-test-suite/P2EQ", fail: true);
case!(case_p76l, "yaml-test-suite/P76L");
case!(case_p94k, "yaml-test-suite/P94K");
case!(case_pbj2, "yaml-test-suite/PBJ2");
case!(case_prh3, "yaml-test-suite/PRH3");
case!(case_puw8, "yaml-test-suite/PUW8");
case!(case_pw8x, "yaml-test-suite/PW8X");
case!(case_q4cl, "yaml-test-suite/Q4CL", fail: true);
case!(case_q5mg, "yaml-test-suite/Q5MG");
case!(case_q88a, "yaml-test-suite/Q88A");
case!(case_q8ad, "yaml-test-suite/Q8AD");
case!(case_q9wf, "yaml-test-suite/Q9WF");
case!(case_qb6e, "yaml-test-suite/QB6E", fail: true);
case!(case_qf4y, "yaml-test-suite/QF4Y");
case!(case_qlj7, "yaml-test-suite/QLJ7", fail: true);
case!(case_qt73, "yaml-test-suite/QT73");
case!(case_r4yg, "yaml-test-suite/R4YG");
case!(case_r52l, "yaml-test-suite/R52L");
case!(case_rhx7, "yaml-test-suite/RHX7", fail: true);
case!(case_rlu9, "yaml-test-suite/RLU9");
case!(case_rr7f, "yaml-test-suite/RR7F");
case!(case_rtp8, "yaml-test-suite/RTP8");
case!(case_rxy3, "yaml-test-suite/RXY3", fail: true);
case!(case_rzp5, "yaml-test-suite/RZP5");
case!(case_rzt7, "yaml-test-suite/RZT7");
case!(case_s3pd, "yaml-test-suite/S3PD");
case!(case_s4gj, "yaml-test-suite/S4GJ", fail: true);
case!(case_s4jq, "yaml-test-suite/S4JQ");
case!(case_s4t7, "yaml-test-suite/S4T7");
case!(case_s7bg, "yaml-test-suite/S7BG");
case!(case_s98z, "yaml-test-suite/S98Z", fail: true);
case!(case_s9e8, "yaml-test-suite/S9E8");
case!(case_sbg9, "yaml-test-suite/SBG9");
case!(case_sf5v, "yaml-test-suite/SF5V", fail: true);
case!(case_ske5, "yaml-test-suite/SKE5");
case!(case_sm9w_00, "yaml-test-suite/SM9W/00");
case!(case_sm9w_01, "yaml-test-suite/SM9W/01");
case!(case_sr86, "yaml-test-suite/SR86", fail: true);
case!(case_ssw6, "yaml-test-suite/SSW6");
case!(case_su5z, "yaml-test-suite/SU5Z", fail: true);
case!(case_su74, "yaml-test-suite/SU74", fail: true);
case!(case_sy6v, "yaml-test-suite/SY6V", fail: true);
case!(case_syw4, "yaml-test-suite/SYW4");
case!(case_t26h, "yaml-test-suite/T26H");
case!(case_t4yy, "yaml-test-suite/T4YY");
case!(case_t5n4, "yaml-test-suite/T5N4");
case!(case_t833, "yaml-test-suite/T833", fail: true);
case!(case_td5n, "yaml-test-suite/TD5N", fail: true);
case!(case_te2a, "yaml-test-suite/TE2A");
case!(case_tl85, "yaml-test-suite/TL85");
case!(case_ts54, "yaml-test-suite/TS54");
case!(case_u3c3, "yaml-test-suite/U3C3");
case!(case_u3xv, "yaml-test-suite/U3XV");
case!(case_u44r, "yaml-test-suite/U44R", fail: true);
case!(case_u99r, "yaml-test-suite/U99R", fail: true);
case!(case_u9ns, "yaml-test-suite/U9NS");
case!(case_udm2, "yaml-test-suite/UDM2");
case!(case_udr7, "yaml-test-suite/UDR7");
case!(case_ugm3, "yaml-test-suite/UGM3");
case!(case_ukk6_00, "yaml-test-suite/UKK6/00");
case!(case_ukk6_01, "yaml-test-suite/UKK6/01");
case!(case_ukk6_02, "yaml-test-suite/UKK6/02");
case!(case_ut92, "yaml-test-suite/UT92");
case!(case_uv7q, "yaml-test-suite/UV7Q");
case!(case_v55r, "yaml-test-suite/V55R");
case!(case_v9d5, "yaml-test-suite/V9D5");
case!(case_vjp3_00, "yaml-test-suite/VJP3/00", fail: true);
case!(case_vjp3_01, "yaml-test-suite/VJP3/01");
case!(case_w42u, "yaml-test-suite/W42U");
case!(case_w4tn, "yaml-test-suite/W4TN");
case!(case_w5vh, "yaml-test-suite/W5VH");
case!(case_w9l4, "yaml-test-suite/W9L4", fail: true);
case!(case_wz62, "yaml-test-suite/WZ62");
case!(case_x38w, "yaml-test-suite/X38W");
case!(case_x4qw, "yaml-test-suite/X4QW", fail: true);
case!(case_x8dw, "yaml-test-suite/X8DW");
case!(case_xlq9, "yaml-test-suite/XLQ9");
case!(case_xv9v, "yaml-test-suite/XV9V");
case!(case_xw4d, "yaml-test-suite/XW4D");
case!(case_y2gn, "yaml-test-suite/Y2GN");
case!(case_y79y_000, "yaml-test-suite/Y79Y/000", fail: true);
case!(case_y79y_001, "yaml-test-suite/Y79Y/001");
case!(case_y79y_002, "yaml-test-suite/Y79Y/002");
case!(case_y79y_003, "yaml-test-suite/Y79Y/003", fail: true);
case!(case_y79y_004, "yaml-test-suite/Y79Y/004", fail: true);
case!(case_y79y_005, "yaml-test-suite/Y79Y/005", fail: true);
case!(case_y79y_006, "yaml-test-suite/Y79Y/006", fail: true);
case!(case_y79y_007, "yaml-test-suite/Y79Y/007", fail: true);
case!(case_y79y_008, "yaml-test-suite/Y79Y/008", fail: true);
case!(case_y79y_009, "yaml-test-suite/Y79Y/009", fail: true);
case!(case_y79y_010, "yaml-test-suite/Y79Y/010");
case!(case_yd5x, "yaml-test-suite/YD5X");
case!(case_yjv2, "yaml-test-suite/YJV2", fail: true);
case!(case_z67p, "yaml-test-suite/Z67P");
case!(case_z9m4, "yaml-test-suite/Z9M4");
case!(case_zcz6, "yaml-test-suite/ZCZ6", fail: true);
case!(case_zf4x, "yaml-test-suite/ZF4X");
case!(case_zh7c, "yaml-test-suite/ZH7C");
case!(case_zk9h, "yaml-test-suite/ZK9H");
case!(case_zl4z, "yaml-test-suite/ZL4Z", fail: true);
case!(case_zvh3, "yaml-test-suite/ZVH3", fail: true);
case!(case_zwk4, "yaml-test-suite/ZWK4");
case!(case_zxt5, "yaml-test-suite/ZXT5", fail: true);
case!(case_2wsf_00, "tests/suite/data/2WSF/00", fail: true);
case!(case_2wsf_01, "tests/suite/data/2WSF/01", fail: true);
case!(case_gldz, "tests/suite/data/GLDZ");
case!(case_qmwa, "tests/suite/data/QMWA", fail: true);
case!(case_r10v_01, "tests/suite/data/R10V/01");
case!(case_r10v_02, "tests/suite/data/R10V/02");
